version: '3.9'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    restart: always
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    platform: linux/x86_64 # por eu estar usando apple silicon
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge